volumes:
  vm-data:
  vmagent-data:
  grafana-data:

services:
  backend:
    build: .
    environment:
      - MQTT_HOST=${MQTT_HOST:-localhost}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    ports:
      - "3000:3000"
    restart: unless-stopped

  victoriametrics:
    image: victoriametrics/victoria-metrics
    volumes:
      - vm-data:/storage
    command:
      - '--storageDataPath=/storage'
      - '--httpListenAddr=:8428'
    restart: unless-stopped

  vmagent:
    image: victoriametrics/vmagent
    depends_on:
      - victoriametrics
    volumes:
      - ./victoriametrics.yaml:/etc/prometheus/prometheus.yaml
      - vmagent-data:/vmagentdata
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yaml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    depends_on:
      - victoriametrics
    restart: unless-stopped

